export const BOOK_CREATE_START = "BOOK_CREATE_START";
export const BOOK_CREATE_SUCCESS = "BOOK_CREATE_SUCCESS";
export const BOOK_CREATE_ERROR = "BOOK_CREATE_ERROR";

export const BOOK_ADD_TO_FAVORITE_START = "BOOK_ADD_TO_FAVORITE_START";
export const BOOK_ADD_TO_FAVORITE_SUCCESS = "BOOK_ADD_TO_FAVORITE_SUCCESS";
export const BOOK_ADD_TO_FAVORITE_ERROR = "BOOK_ADD_TO_FAVORITE_ERROR";

export const BOOK_GET_ALL_START = "BOOK_GET_ALL_START";
export const BOOK_GET_ALL_SUCCESS = "BOOK_GET_ALL_SUCCESS";
export const BOOK_GET_ALL_ERROR = "BOOK_GET_ALL_ERROR";
