export const BOOK_LOADING_START = "BOOK_LOADING_START";
export const BOOK_GET_SUCCESS = "BOOK_GET_SUCCESS";
export const BOOK_LOADING_ERROR = "BOOK_LOADING_ERROR";

export const BOOK_ADD_START = "BOOK_ADD_START";
export const BOOK_ADD_SUCCESS = "BOOK_ADD_SUCCESS";
export const BOOK_ADD_ERROR = "BOOK_ADD_ERROR";
