export const BOOK_ADD = "BOOK_ADD";
export const BOOK_ADD_TO_FAVORITE = "BOOK_ADD_TO_FAVORITE";

export const BOOK_LOADING_START = "BOOK_LOADING_START";
export const BOOK_GET_SUCCESS = "BOOK_GET_SUCCESS";
export const BOOK_LOADING_ERROR = "BOOK_LOADING_ERROR";
